#!/usr/bin/env julia
"""
    bench/derive_coeffs.jl

Write conservative cost-model coefficients for a cluster that has not been
calibrated, by derating a cluster that has.

    julia bench/derive_coeffs.jl --target nibi --donor fir
    julia bench/derive_coeffs.jl --all          # every entry in DERIVED

This exists because standing up a new cluster should not mean submitting jobs
with the built-in analytic guesses. A measured machine with the same GPU, derated
for the CPU difference, is a far better starting point -- and unlike a hand-typed
table, the derivation is reproducible and its provenance ends up in the generated
file.

`bench/fit.jl` overwrites `coeffs_<cluster>.jl` as soon as that cluster has real
calibration rows, so these are strictly a stopgap.

# What gets derated, and why in that direction

Time coefficients are scaled so the model predicts jobs taking *longer* on the
target than the donor. Underestimating time gets the job killed after it has done
most of the work; overestimating costs some queue position. The asymmetry is not
close, so every factor here errs the same way.

  * `cpu_derate` multiplies the Green-function job's per-cell and fixed costs.
    Nibi's Xeon 6 "Granite Rapids" and rorqual's Genoa should both be at least as
    fast per core as fir's EPYC 9454, so 1.5x is margin rather than a correction.
  * `gpu_derate` divides the fitted throughput rates and multiplies the
    per-matvec times. All three machines carry H100 SXM 80GB parts, so the honest
    factor is 1.0; 1.25 leaves room for a different binning, a different CUDA
    version, or a busier node.

Memory coefficients are **not** derated. They are array bytes plus a process
baseline: the same code allocating the same arrays on the same 80 GB card. The
measured host-RAM fit was 0.99x the analytic count plus 2.3 GiB, and the measured
process baselines agreed within 15% across three different machines.
"""

include(joinpath(@__DIR__, "cost_model.jl"))
using .CostModel
using Dates
using Printf

"""
    DERIVED

Targets, their donor, and the derating factors. Keep the reasoning next to the
numbers so the next person can tell a measurement from a judgement call.
"""
const DERIVED = [
    (target="nibi", donor="fir", cpu_derate=1.5, gpu_derate=1.25,
     note="8x H100 SXM 80GB per node, 112 Intel Xeon 6 (Granite Rapids) cores. " *
          "Xeon 6 should match or beat fir's EPYC 9454, so the CPU derate is " *
          "pure margin. Bundle is 14 cores and 250 GB per GPU."),
    (target="rorqual", donor="fir", cpu_derate=1.5, gpu_derate=1.25,
     note="4x H100 SXM5 80GB per node, 64 AMD Genoa cores. Same GPU generation " *
          "as fir. Bundle is 16 cores and 124.5 GB per GPU."),
]

"Coefficient fields that are a *time per unit of work*: derate by multiplying."
const CPU_TIME_FIELDS = (:g0_self_fft, :g0_self_cell, :g0_self_fixed,
                         :g0_ext_fft, :g0_ext_cell, :g0_ext_fixed,
                         :g0_contact_fft, :g0_contact_cell, :g0_contact_fixed,
                         :g0_startup_s)
const GPU_TIME_FIELDS = (:mv_self_fft, :mv_self_fixed, :mv_ext_fft, :mv_ext_fixed,
                         :launch_latency, :sync_latency, :host_root_find,
                         :gpu_startup_s)
"Coefficient fields that are a *rate*: derate by dividing."
const GPU_RATE_FIELDS = (:qr_rate, :gemm_rate, :eigh_rate, :geigh_rate,
                         :svdvals_rate, :bandwidth)

function derive(donor::Coefficients, target::AbstractString,
                cpu_derate::Real, gpu_derate::Real)
    fields = Dict{Symbol,Any}(f => getfield(donor, f) for f in fieldnames(Coefficients))
    fields[:name] = target
    # Not "calibrated": nothing here was measured on this machine.
    fields[:calibrated] = false
    for f in CPU_TIME_FIELDS
        fields[f] = getfield(donor, f) * cpu_derate
    end
    for f in GPU_TIME_FIELDS
        fields[f] = getfield(donor, f) * gpu_derate
    end
    for f in GPU_RATE_FIELDS
        fields[f] = getfield(donor, f) / gpu_derate
    end
    return Coefficients(; (k => v for (k, v) in fields)...)
end

function write_derived(entry; dir::AbstractString=@__DIR__)
    donor = coefficients_for(entry.donor)
    donor.calibrated ||
        @warn "Donor '$(entry.donor)' is not itself calibrated; the derived coefficients for '$(entry.target)' inherit its guesses."
    coeffs = derive(donor, entry.target, entry.cpu_derate, entry.gpu_derate)
    path = joinpath(dir, "coeffs_$(entry.target).jl")
    open(path, "w") do io
        println(io, "# Generated by bench/derive_coeffs.jl on $(Dates.now()).")
        println(io, "#")
        println(io, "# NOT MEASURED ON $(uppercase(entry.target)). Derived from $(entry.donor)'s")
        println(io, "# calibration, derated to err towards over-estimating:")
        println(io, "#   CPU time coefficients x $(entry.cpu_derate)")
        println(io, "#   GPU time coefficients x $(entry.gpu_derate), GPU rates / $(entry.gpu_derate)")
        println(io, "#   memory coefficients unchanged (same code, same 80 GB card)")
        println(io, "#")
        for line in split(entry.note, r"(?<=\. )")
            isempty(strip(line)) || println(io, "# $(strip(line))")
        end
        println(io, "#")
        println(io, "# Replace this by calibrating for real:")
        println(io, "#   julia bench/plan.jl --cluster $(entry.target) --tier quick")
        println(io, "#   julia bench/plan.jl --cluster $(entry.target) --tier memory")
        println(io, "# then rerun bench/fit.jl, which will overwrite this file.")
        println(io)
        println(io, "CostModel.Coefficients(")
        for field in fieldnames(Coefficients)
            value = getfield(coeffs, field)
            literal = value isa String ? "\"$value\"" :
                      value isa Bool ? string(value) : @sprintf("%.10g", value)
            println(io, "    $field = $literal,")
        end
        println(io, ")")
    end
    return path, coeffs
end

function main(argv::Vector{String})
    opts = Dict{String,String}()
    i = 1
    while i <= length(argv)
        startswith(argv[i], "--") || error("Expected an option, got '$(argv[i])'")
        key = argv[i][3:end]
        if i + 1 <= length(argv) && !startswith(argv[i + 1], "--")
            opts[key] = argv[i + 1]; i += 2
        else
            opts[key] = "true"; i += 1
        end
    end

    load_coefficients!(@__DIR__)

    entries = if haskey(opts, "all") || !haskey(opts, "target")
        DERIVED
    else
        target = opts["target"]
        found = filter(e -> e.target == target, DERIVED)
        if isempty(found)
            donor = get(opts, "donor", "fir")
            [(target=target, donor=donor,
              cpu_derate=parse(Float64, get(opts, "cpu-derate", "1.5")),
              gpu_derate=parse(Float64, get(opts, "gpu-derate", "1.25")),
              note="Ad hoc derivation from $donor.")]
        else
            found
        end
    end

    for entry in entries
        path, coeffs = write_derived(entry)
        println("Wrote $path")
        @printf("  from %-9s cpu x%.2f  gpu x%.2f   (g0_ext_cell %.3g s, qr_rate %.3g flop/s)\n",
                entry.donor, entry.cpu_derate, entry.gpu_derate,
                coeffs.g0_ext_cell, coeffs.qr_rate)
    end
    println()
    println("These are stopgaps. Calibrate for real with:")
    for entry in entries
        println("  julia bench/plan.jl --cluster $(entry.target) --tier quick")
    end
    return nothing
end

if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end
